# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fcd09d3f7c4eef3dc00d54fc1a8e5935dd1527beb5b1debecb8d9296336a72144da3253c01a322846b968cef9a82e3e7260d86b13a9bc61367aa3e8ab8f8a53

test:
  secret_key_base: 8cdd928945c75c6ff763aa24c26193cfcce38cfd58662a0a8f04117b33d1c48775b59c4cef86e110e608e5aa29ed26edcc7f097b5b74e149fa2c27c25b0a2e63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
